# Generated by Django 4.2.29 on 2026-07-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingbatch',
            name='output_units',
            field=models.PositiveIntegerField(help_text='Number of packs produced — added to variant stock on confirm'),
        ),
    ]
