# Generated by Django 4.2.29 on 2026-07-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodulepermission',
            name='module',
            field=models.CharField(choices=[('orders_payments', 'Orders & Payments'), ('accounts_users', 'Accounts & Users'), ('catalog_reviews', 'Catalog & Reviews'), ('procurement', 'Procurement & Processing'), ('payroll', 'Staff Payroll')], max_length=30),
        ),
    ]
